name: Build .exe Workflow
on:
  push:
    branches: 
    - main

env:
  PYTHON_VERSION: 3.12
  ARCHITECTURE: x64
  EXE_FILE_NAME: timeit
  ARTIFACT_NAME: TimeiT
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: $PYTHON_VERSION
          architecture: $ARCHITECTURE
          
      - name: Display Python version
        run: echo "Using Python $PYTHON_VERSION"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Upgrade setuptools
        run: python -m pip install --upgrade setuptools

      - name: Install dependencies
        run: pip install -r ./docs/requirements.txt

      - name: Run PyInstaller
        run: pyinstaller -w -F --name $EXE_FILE_NAME --distpath d:\dist\ .\src\main.py --version-file .\docs\file_version_info.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: $ARTIFACT_NAME
          path: $EXE_FILE_NAME.exe
         
        