name: Build .exe Workflow
on:
  push:
    branches: 
    - main

env:
  EXE_FILE_NAME: 'timeit'
  ARTIFACT_NAME: 'TimeiT'
  
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
          architecture: "x64"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Upgrade setuptools
        run: python -m pip install --upgrade setuptools

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Run PyInstaller
        run: pyinstaller --name timeit --onefile --target-arch x64 --distpath d:\dist\ --path .\src --collect-all=classes .\src\main.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: TimeiT
          path: d:\dist\timeit.exe

      - name: Upload release asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "d:/dist/timeit.exe"
          body: "Adding squad select option for your hours!"
          name: "TimeiT v1.2.0"
          tag: "v1.2.0"

  deploy:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.0"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r ./requirements-mkdocs.txt

      - name: Actions Cache
        uses: actions/cache@v4.1.1
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: MKDOCS Deploy
        run: mkdocs gh-deploy --force --config-file ./docs/en/mkdocs.yml
